services:
  postgres:
    image: postgres
    environment: 
    - POSTGRES_DATABASE=postgres
    - POSTGRES_USERNAME=postgres
    - POSTGRES_PASSWORD=postgres
    # volumes:
    # - ./mnt:/var/lib/postgresql/data
    ports: 
    - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 15672:15672